version: "3.9"

services:
  store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store_container
    ports:
      - "8008:8008"
    volumes:
      #- ./store:/store
      - ./store:/app/store
    env_file:
      - .env
    command: bash -c "store/manage.py runserver 0.0.0.0:8008"

volumes:
  static_volume:
  media_volume:
